import { AccommodationUnit } from "@/entities/accommodation-unit/model/types";

export const data: AccommodationUnit[] = [
    {
        id: "1",
        accId: "1",
        unitType: "APARTMENT",
        name: "С302",
        description: "Квартира с ремонтом в классическом стиле. Вблизи ТРЦ Shymkent Plaza.",
        capacity: 3,
        area: 65,
        floor: 2,
        isAvailable: true,
    },
    {
        id: "2",
        accId: "1",
        unitType: "ROOM",
        name: "B104",
        description: "Уютная комната с балконом и видом на сад. Тихий район.",
        capacity: 2,
        area: 25,
        floor: 1,
        isAvailable: false,
    },
    {
        id: "3",
        accId: "2",
        unitType: "APARTMENT",
        name: "A501",
        description: "Современные апартаменты с просторной гостиной и кухней-студией.",
        capacity: 4,
        area: 78,
        floor: 5,
        isAvailable: true,
    },
    {
        id: "4",
        accId: "2",
        unitType: "ROOM",
        name: "D210",
        description: "Комната с кондиционером и личной ванной. Идеально для студентов.",
        capacity: 1,
        area: 18,
        floor: 2,
        isAvailable: true,
    },
    {
        id: "5",
        accId: "3",
        unitType: "STUDIO",
        name: "E407",
        description: "Студия с панорамными окнами и современной мебелью.",
        capacity: 2,
        area: 35,
        floor: 4,
        isAvailable: false,
    },
    {
        id: "6",
        accId: "3",
        unitType: "ROOM",
        name: "C208",
        description: "Светлая комната с минималистичным интерьером и удобной кроватью.",
        capacity: 1,
        area: 20,
        floor: 2,
        isAvailable: true,
    },
];
