name: Build and Deploy Frontend UI Tap

on:
  push:
    branches:
      - main

jobs:
  build-and-push-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image
        run: docker build . --tag mobkus837/ui-tap-front:latest 

      - name: Log in to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u mobkus837 --password-stdin

      - name: Push to Docker Hub
        run: docker push mobkus837/ui-tap-front:latest
  
  
  deploy-to-server:
    runs-on: ubuntu-latest
    needs: build-and-push-docker-image
    steps:
      - name: Deploy to Server using Docker Compose
        uses: appleboy/ssh-action@v0.1.8
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            cd inlive
            echo "Pulling latest Docker image..."
            docker pull mobkus837/ui-tap-front:latest

            echo "Stopping and removing old containers..."
            docker-compose stop ui-tap-front
            docker-compose rm -f ui-tap-front
            
            echo "Starting up containers with Docker Compose..."
            docker-compose up -d ui-tap-front
            
            echo "Cleaning up unused Docker images..."
            docker image prune -af  
            
            
            echo "Deployment completed!"
            
